name: ci
# 名称
on:
# 指定触发事件，并限定分支为master。
  push:
    branches:
      - "main"

jobs:
  # 取docker为job_id
  docker:
    # 定义环境在ubantu中运行
    runs-on: ubuntu-latest

    steps:
    #运行流程，按顺序执行
    #uses表示使用别人写好的命令，这里用Docker Hub 上的现有操作
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        #with附带参数
        #设置/settings/secrets。在“ 秘密”选项卡中，添加DOCKER_USERNAME和DOCKER_PASSWORD秘密密钥
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zhourunpo/mosad-server:latest